import React from 'react';
import { Card, CardContent, Typography, Box, Divider, Grid, Paper, Tooltip as MuiTooltip } from '@mui/material';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer } from 'recharts';

interface ReportData {
    forecast?: { date: string; value: number }[];
    inventory?: { warehouse: string; stock: number; capacity: number }[];
    summary?: string;
}

interface ReportDashboardProps {
    data: ReportData | null;
}

export const ReportDashboard: React.FC<ReportDashboardProps> = ({ data }) => {
    if (!data) {
        return (
            <Card sx={{ height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <Typography color="textSecondary">No report data generated yet.</Typography>
            </Card>
        );
    }

    return (
        <Card sx={{ height: '100%', overflow: 'auto' }}>
            <CardContent>
                <Typography variant="h6" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                    <MuiTooltip title="Executive summary of agent execution results" arrow>
                        <span style={{ cursor: 'help' }}>Analysis Report</span>
                    </MuiTooltip>
                </Typography>
                <Typography variant="body2" sx={{ mb: 2 }}>{data.summary || 'Post-workflow analysis generated by Reporting Agent.'}</Typography>

                <Divider sx={{ my: 2 }} />

                {data.forecast && (
                    <Box sx={{ mb: 4 }}>
                        <Typography variant="subtitle2" gutterBottom>Demand Forecast (Next 3 Months)</Typography>
                        <Box sx={{ height: 200, width: '100%' }}>
                            <ResponsiveContainer>
                                <BarChart data={data.forecast}>
                                    <CartesianGrid strokeDasharray="3 3" />
                                    <XAxis dataKey="date" />
                                    <YAxis />
                                    <RechartsTooltip />
                                    <Bar dataKey="value" fill="#2196f3" radius={[4, 4, 0, 0]} />
                                </BarChart>
                            </ResponsiveContainer>
                        </Box>
                    </Box>
                )}

                {data.inventory && (
                    <Grid container spacing={1}>
                        {data.inventory.map((item, i) => (
                            <Grid item xs={12} key={i}>
                                <MuiTooltip title={`Current stock level for ${item.warehouse} warehouse vs maximum capacity.`} arrow placement="left">
                                    <Paper variant="outlined" sx={{ p: 1, bgcolor: 'rgba(255,255,255,0.05)', cursor: 'help' }}>
                                        <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.5 }}>
                                            <Typography variant="caption" fontWeight="bold">{item.warehouse}</Typography>
                                            <Typography variant="caption">{item.stock} / {item.capacity}</Typography>
                                        </Box>
                                        <Box sx={{ height: 4, width: '100%', bgcolor: 'rgba(255,255,255,0.1)', borderRadius: 2 }}>
                                            <Box
                                                sx={{
                                                    height: '100%',
                                                    width: `${(item.stock / item.capacity) * 100}%`,
                                                    bgcolor: item.stock > item.capacity * 0.8 ? '#f44336' : '#4caf50',
                                                    borderRadius: 2
                                                }}
                                            />
                                        </Box>
                                    </Paper>
                                </MuiTooltip>
                            </Grid>
                        ))}
                    </Grid>
                )}
            </CardContent>
        </Card>
    );
};
